
title: "GeoStation"
author: Mohammed Almusidi

sphinx:
  extra_extensions:
    - sphinx_sitemap

  config:
    html_baseurl: "https://malmusidi.github.io/GeoStation/"
    sitemap_url_scheme: "{link}"
    
    


exclude_patterns:
  - "tutorials/NOAA_Temperature_Data.ipynb"
  - "tutorials/Riyadh_Road_Network.ipynb"

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/Malmusidi/GeoStation  # Online location of your book
  path_to_book: mybook  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)





# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  numbered: true

  use_issues_button: true

  use_repository_button: true

  logo: _static/logo1.png


copyright: "2025"