name: Build & Deploy Jupyter-Book

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the main branch, but do NOT persist the default token
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2) Set up Python (any 3.x will do)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install Jupyter-Book and the ghp-import tool
      - name: Install dependencies
        run: pip install jupyter-book ghp-import

      # 4) Build your book in-place under mybook/_build/html
      - name: Build book
        run: |
          jupyter-book clean mybook
          jupyter-book build mybook

      # 5) Publish the built HTML to gh-pages, using the GITHUB_TOKEN
      - name: Publish to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ghp-import -n -p -f mybook/_build/html
