name: Build & Deploy Jupyter-Book

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repo and keep the GITHUB_TOKEN so we can push later
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      # 2) Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install Jupyter-Book and the ghp-import tool
      - name: Install dependencies
        run: |
          pip install jupyter-book ghp-import

      # 4) Build the book in the mybook folder
      - name: Build book
        run: |
          jupyter-book clean mybook
          jupyter-book build mybook

      # 5) Publish the built HTML to the gh-pages branch
      - name: Publish to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ghp-import -n -p -f mybook/_build/html